#!/bin/bash

dir=$(pwd)
subdir=${dir##*/}

if [[ -z $GH_USER ]] || [[ -z $GH_PASS ]]; then
    echo "you need to set environment variables GH_USER and GH_PASS"
    echo "use your Github Enterprise username as GH_USER"
    echo "create and use a GH Personal Access Token as GH_PASS"
    echo "see https://github.ibm.com/settings/tokens"
    exit 1
fi

if [[ $# -eq 0 ]] || [[ "$subdir" != "journey-template" ]]; then
    echo $0
    echo "Usage:"
    echo "git clone git@github.ibm.com:om-docs/journey-template.git"
    echo "$ cd journey-template"
    echo "$ ./scripts/new_journey name-of-new-journey"
    exit 1
fi

JOURNEY=$1


echo "Checking for Python"

if ! python -V > /dev/null; then
  echo "  could not find python on your system"
fi

if ! pip show PyGithub > /dev/null; then
  echo "    python requirements not installed.  run:"
  echo "    $ sudo pip install PyGithub"
fi

if [[ -e scripts/new_journey_create_repo ]]; then
  scripts/new_journey_create_repo ${JOURNEY} || exit 1
else
  echo "could not locate scripts/new_journey_create_repo"
  echo "you will need to run that manually to finish"
  exit 1
fi

cd ..

if [ -d journey-template ]; then
  if [ -d ${JOURNEY} ]; then
    echo ${JOURNEY} already exists
    exit 1
  fi
  echo "copying journey from template"
  cp -R journey-template ${JOURNEY}
  echo "updating git origin"
  cd ${JOURNEY}
  git remote remove origin
  git remote add origin git@github.ibm.com:om-docs/${JOURNEY}
  git push origin master
else
  pwd
  echo something went wrong
  exit 1
fi
